name: CI tests

on:
  push:

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        redis-version: [5, 6]

    steps:
    - uses: actions/checkout@v2
    
    - uses: php-actions/composer@v5

    - name: Start Redis
      uses: supercharge/redis-github-action@1.2.0
      with:
        redis-version: ${{ matrix.redis-version }}    
 
    - name: Install redis-cli
      run: sudo apt-get update && sudo apt-get install redis-tools -y

    - name: PHPUnit tests
      uses: php-actions/phpunit@v3
      with:
        configuration: phpunit.xml
        memory_limit: 256M
