name: CI tests

on:
  push:

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        redis-version:
          - '6.0'
          - '5.0'

    name: "Test emitter with ${{matrix.redis-version}}"
    steps:
    - uses: actions/checkout@v2
    
    - uses: php-actions/composer@v5

    - uses: shogo82148/actions-setup-redis@v1
      with:
        redis-version: ${{ matrix.redis-version }}
 
    - name: PHPUnit tests
      uses: php-actions/phpunit@v3
      with:
        configuration: phpunit.xml
        memory_limit: 256M
